/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { DecentralizedIdentityManager__factory } from "./DecentralizedIdentityManager__factory";
