/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DecentralizedIdentityManager } from "./DecentralizedIdentityManager";
export * as factories from "./factories";
export { DecentralizedIdentityManager__factory } from "./factories/DecentralizedIdentityManager__factory";
export type { IDecentralizedIdentityManager } from "./interfaces/IDecentralizedIdentityManager";
export { IDecentralizedIdentityManager__factory } from "./factories/interfaces/IDecentralizedIdentityManager__factory";
