/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDecentralizedIdentityManager,
  IDecentralizedIdentityManagerInterface,
} from "../../interfaces/IDecentralizedIdentityManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "nickname",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "publicKey",
        type: "bytes32",
      },
    ],
    name: "createUser",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userId",
        type: "address",
      },
    ],
    name: "getUser",
    outputs: [
      {
        internalType: "bytes32",
        name: "nickname",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "publicKey",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "registrationTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastUpdateTime",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userId",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "nickname",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "publicKey",
        type: "bytes32",
      },
    ],
    name: "updateUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userId",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "messageHash",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "verifyUserSignature",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDecentralizedIdentityManager__factory {
  static readonly abi = _abi;
  static createInterface(): IDecentralizedIdentityManagerInterface {
    return new utils.Interface(_abi) as IDecentralizedIdentityManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDecentralizedIdentityManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDecentralizedIdentityManager;
  }
}
